permalink: /:year:month:day/:title
url: https://calcul.digital
baseurl: /project

# variables
name: Mașina de Calcul
description: Fie că ești dezvoltator, expert în securitate sau simplu entuziast, site-ul nostru îți oferă cele mai noi informații și unelte necesare pentru a rămâne la curent cu dinamica rapidă a tehnologiei. Alătură-te comunității noastre și transformă pasiunea ta într-o aventură continuă de învățare și descoperire.
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
